# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'macros.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(540, 561)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.add_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_btn.setGeometry(QtCore.QRect(10, 10, 141, 41))
        self.add_btn.setObjectName("add_btn")
        self.del_btn = QtWidgets.QPushButton(self.centralwidget)
        self.del_btn.setGeometry(QtCore.QRect(10, 60, 141, 41))
        self.del_btn.setObjectName("del_btn")
        self.change_btn = QtWidgets.QPushButton(self.centralwidget)
        self.change_btn.setGeometry(QtCore.QRect(10, 110, 141, 41))
        self.change_btn.setObjectName("change_btn")
        self.macros_table = QtWidgets.QTableWidget(self.centralwidget)
        self.macros_table.setGeometry(QtCore.QRect(160, 10, 371, 511))
        self.macros_table.setMinimumSize(QtCore.QSize(261, 501))
        self.macros_table.setMaximumSize(QtCore.QSize(411, 511))
        self.macros_table.setObjectName("macros_table")
        self.macros_table.setColumnCount(3)
        self.macros_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.macros_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.macros_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.macros_table.setHorizontalHeaderItem(2, item)
        self.macros_table.horizontalHeader().setCascadingSectionResizes(False)
        self.macros_table.horizontalHeader().setDefaultSectionSize(122)
        self.macros_table.horizontalHeader().setMinimumSectionSize(49)
        self.macros_table.horizontalHeader().setSortIndicatorShown(False)
        self.macros_table.horizontalHeader().setStretchLastSection(False)
        self.macros_table.verticalHeader().setCascadingSectionResizes(False)
        self.macros_table.verticalHeader().setDefaultSectionSize(33)
        self.macros_table.verticalHeader().setMinimumSectionSize(23)
        self.macros_table.verticalHeader().setSortIndicatorShown(False)
        self.macros_table.verticalHeader().setStretchLastSection(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 540, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Макросы"))
        self.add_btn.setText(_translate("MainWindow", "Добавить макрос"))
        self.del_btn.setText(_translate("MainWindow", "Удалить макрос"))
        self.change_btn.setText(_translate("MainWindow", "Изменить макрос"))
        self.macros_table.setSortingEnabled(False)
        item = self.macros_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Название макроса"))
        item = self.macros_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Комбинация клавиш"))
        item = self.macros_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Название файла"))
