# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'macros.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(483, 561)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.add_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_btn.setGeometry(QtCore.QRect(10, 10, 201, 41))
        self.add_btn.setObjectName("add_btn")
        self.del_btn = QtWidgets.QPushButton(self.centralwidget)
        self.del_btn.setGeometry(QtCore.QRect(10, 60, 201, 41))
        self.del_btn.setObjectName("del_btn")
        self.change_btn = QtWidgets.QPushButton(self.centralwidget)
        self.change_btn.setGeometry(QtCore.QRect(10, 110, 201, 41))
        self.change_btn.setObjectName("change_btn")
        self.macros_table = QtWidgets.QTableWidget(self.centralwidget)
        self.macros_table.setGeometry(QtCore.QRect(230, 10, 241, 501))
        self.macros_table.setObjectName("macros_table")
        self.macros_table.setColumnCount(0)
        self.macros_table.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 483, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Макросы"))
        self.add_btn.setText(_translate("MainWindow", "Добавить макрос"))
        self.del_btn.setText(_translate("MainWindow", "Удалить макрос"))
        self.change_btn.setText(_translate("MainWindow", "Изменить макрос"))
