# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'macros.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 442)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 831, 391))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.add_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.add_btn.setObjectName("add_btn")
        self.gridLayout.addWidget(self.add_btn, 0, 0, 1, 1)
        self.macros_table = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.macros_table.setObjectName("macros_table")
        self.macros_table.setColumnCount(5)
        self.macros_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.macros_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.macros_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.macros_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.macros_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.macros_table.setHorizontalHeaderItem(4, item)
        self.macros_table.horizontalHeader().setDefaultSectionSize(115)
        self.macros_table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.macros_table, 4, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.del_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.del_btn.setObjectName("del_btn")
        self.horizontalLayout.addWidget(self.del_btn)
        self.change_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.change_btn.setObjectName("change_btn")
        self.horizontalLayout.addWidget(self.change_btn)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 0, 1, 1)
        self.tray_cb = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.tray_cb.setObjectName("tray_cb")
        self.gridLayout.addWidget(self.tray_cb, 6, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 850, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Макросы"))
        self.add_btn.setText(_translate("MainWindow", "Добавить макрос"))
        item = self.macros_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Название макроса"))
        item = self.macros_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Сочетание клавиш"))
        item = self.macros_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Имя файла"))
        item = self.macros_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Работоспособность"))
        item = self.macros_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Адрес файла"))
        self.del_btn.setText(_translate("MainWindow", "Активитовать/деактевировать выбранный(е) макрос(ы)"))
        self.change_btn.setText(_translate("MainWindow", "Подтвердить изменения макроса(ов)"))
        self.tray_cb.setText(_translate("MainWindow", "Сворачивать в трей при закрытии"))
